services:
  # The unified single image build target
  file-ingestion-service:
    image: ghcr.io/arshavin023/lamisplus-records-ingestion:v1.4
    build:
      context: .
      dockerfile: ./records_ingestion/Dockerfile
    user: "${UID}:${GID}"
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=${PYTHONUNBUFFERED:-1}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ${FILE_DIRECTORY}:${FILE_DIRECTORY}
      - ./records_ingestion/logs:/app/records_ingestion/logs
    restart: "no"
    # This acts as the default command if none is provided
    # command: python records_ingestion/multi_file_ingestion_process.py

  records-deletion-service:
    image: ghcr.io/arshavin023/lamisplus-records-deletion:v1.0
    build:
      context: .
      dockerfile: ./records_deletion/Dockerfile
    user: "${UID}:${GID}"
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=${PYTHONUNBUFFERED:-1}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./records_deletion/logs:/app/records_deletion/logs
    restart: "no"

  file-deletion-service:
    image: ghcr.io/arshavin023/lamisplus-file-deletion:v1.1
    build:
      context: .
      dockerfile: ./file_deletion/Dockerfile
    user: "${UID}:${GID}"
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=${PYTHONUNBUFFERED:-1}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ${FILE_DIRECTORY}:${FILE_DIRECTORY}
      - ./file_deletion/logs:/app/file_deletion/logs
    restart: "no"
