name: Deploy Data Pipeline

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Server via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: lamisplus
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            set -e
            cd /home/lamisplus/lamisplus_ingestion
            git pull origin main

            # Enforce unquoted EOF to let GitHub replace the secrets before execution
            cat << EOF > .env
            DB_USER=${{ secrets.DB_USER }}
            DB_PASSWORD=${{ secrets.DB_PASSWORD }}
            DB_PORT=${{ secrets.DB_PORT }}
            DB_NAME_FILEDB=${{ secrets.DB_NAME_FILEDB }}
            DB_NAME_LAMISPLUS_STAGING_DWH=${{ secrets.DB_NAME_LAMISPLUS_STAGING_DWH }}
            FILE_DIRECTORY=${{ secrets.FILE_DIRECTORY }}
            UID=${{ secrets.UID }}
            GID=${{ secrets.GID }}
            EOF

            # Log in to GHCR cleanly
            echo "${{ secrets.CR_PAT }}" | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin

            # Pull updates, recreate infrastructure, and spin the app back up
            docker compose pull
            docker compose down --remove-orphans
            docker compose up -d

            echo "Deployment successful!"